# SPDX-License-Identifier: LGPL-2.1-or-later

using JuMinuit
using Test

@testset "JuMinuit.jl" verbose = true begin
    include("test_precision.jl")
    include("test_strategy.jl")
    include("test_state.jl")
    include("test_fcn.jl")
    include("test_linalg.jl")
    include("test_gradient.jl")
    include("test_davidon.jl")
    include("test_edm.jl")
    include("test_posdef.jl")
    include("test_linesearch.jl")
    include("test_negative_g2.jl")
    include("test_seed.jl")
    include("test_migrad.jl")
    include("test_cpp_oracle.jl")
    include("test_aqua_jet.jl")
    include("test_transform.jl")
    include("test_parameters.jl")
    include("test_hesse.jl")
    include("test_hesse_strategy.jl")
    include("test_covariance_squeeze.jl")
    include("test_minos.jl")
    include("test_minos_oracle.jl")
    include("test_bounded_gauss_minos.jl")
    include("test_contour_oracle.jl")
    include("test_hesse_oracle.jl")
    include("test_contours.jl")
    include("test_migrad_bounded.jl")
    include("test_minuit.jl")
    include("test_display.jl")
    include("test_minuit_mutators.jl")
    include("test_param_views.jl")
    include("test_minuit_retry.jl")
    include("test_ad_gradient.jl")
    include("test_serialize.jl")
    include("test_contour_exact.jl")
    include("test_threaded_gradient.jl")
    include("test_plot_recipes.jl")
    include("test_plot_text.jl")
    include("test_iminuit_compat.jl")
    include("test_iminuit_compat_data.jl")
    include("test_cost_functions.jl")
    include("test_resampling_errors.jl")
    include("test_simplex_scan.jl")
    include("test_error_sampling.jl")
    include("test_eigen_corr.jl")
    include("test_phase1_cleanup.jl")
    include("test_print_level.jl")
end
