# SPDX-License-Identifier: LGPL-2.1-or-later
#
# MINOS crossing-search parity with C++ Minuit2 (MnFunctionCross).
#
# Reference: test/reference_data/minos_parity_cpp.json, generated by
# tools/minos_parity_trace.cxx against the pinned Minuit2 6.24.0 (MIGRAD +
# HESSE + MINOS at Strategy(1), tol 0.1) on five generic problems whose data
# are the minos_parity_*.txt files next to it. Each objective is wrapped in
# a counting FCN that records the scanned parameter's value per call during
# MINOS, so the inner minimisations ("probes") of the crossing search are
# observable on both sides without instrumenting the algorithm.
#
# What is pinned:
#  1. Crossing quality. For each end point x̂ ± δ, fixing the parameter there
#     and re-minimising the rest (Strategy(2), tol 1e-4) gives
#     q = (F_profile − F_min)/up; a perfect crossing has q = 1. Through
#     v0.7.3 the search substituted a fictitious point for the α=0 inner
#     MIGRAD and had no quadratic early exit, which biased the end points
#     by up to the 0.01·up crossing tolerance (|q−1| ≈ 1e-2); Minuit2 and
#     the C++-faithful port reach ≲ 1e-4.
#  2. The Gaussian problem has closed-form profile-likelihood intervals
#     (means: x̄ ± s·√(e^{1/n} − 1); widths: n·ln(σ/s) + n/2·(s²/σ² − 1) = 1/2),
#     compared as end-point POSITIONS so the MIGRAD minimum's own
#     displacement is included, as in the external benchmark.
#  3. The probe sequence (number of inner minimisations per parameter) equals
#     the C++ one, and the MINOS end points agree with C++ to the inner-MIGRAD
#     tolerance. Total FCN calls are at most the C++ count: NativeMinuit
#     warm-restarts the inner MIGRAD from the previous probe's gradient steps
#     and covariance and skips the iteration when the seed is already
#     converged (see `_migrad_loop`), where C++ re-seeds the gradient from the
#     parameter errors and always runs one line search — a documented,
#     deliberate difference in cost per probe, not in the crossing found.

using JSON
# Whitespace-separated numeric table (the minos_parity_*.txt data files),
# read without DelimitedFiles (not a standard library since Julia 1.9).
function _mp_readrows(path)
    rows = [parse.(Float64, split(l)) for l in eachline(path) if !isempty(strip(l))]
    return permutedims(reduce(hcat, rows))
end

const _MP_DIR = joinpath(@__DIR__, "reference_data")
const _MP_REF = JSON.parsefile(joinpath(_MP_DIR, "minos_parity_cpp.json"))

# ── The five problems (identical to tools/minos_parity_trace.cxx) ──────────
let gauss = _mp_readrows(joinpath(_MP_DIR, "minos_parity_gauss5.txt")),
    bw = _mp_readrows(joinpath(_MP_DIR, "minos_parity_bw6.txt")),
    ex = _mp_readrows(joinpath(_MP_DIR, "minos_parity_exp2.txt")),
    H = _mp_readrows(joinpath(_MP_DIR, "minos_parity_quad4_H.txt"))

    global _mp_rosen(p) = (1 - p[1])^2 + 100 * (p[2] - p[1]^2)^2
    global function _mp_quad4(p)
        s = 0.0
        for i in 1:4, j in 1:4
            s += 0.5 * p[i] * H[i, j] * p[j]
        end
        s
    end
    global function _mp_gauss(p)
        s = 0.0
        @inbounds for r in 1:size(gauss, 1)
            k = Int(gauss[r, 1]); mu = p[2k + 1]; sg = p[2k + 2]
            sg <= 0 && return 1e30
            d = gauss[r, 2] - mu
            s += log(sg) + 0.5 * d * d / (sg * sg)
        end
        s
    end
    global function _mp_bw(p)
        s = 0.0
        @inbounds for r in 1:size(bw, 1)
            x = bw[r, 1]
            m = p[1] * (p[3] * p[3] / 4) / ((x - p[2])^2 + p[3] * p[3] / 4) +
                p[4] + p[5] * (x - 5) + p[6] * (x - 5)^2
            d = (bw[r, 2] - m) / 0.05
            s += d * d
        end
        s
    end
    global function _mp_exp(p)
        s = 0.0
        @inbounds for r in 1:size(ex, 1)
            m = p[1] * exp(-ex[r, 1] / p[2]); d = (ex[r, 2] - m) / 0.02
            s += d * d
        end
        s
    end
    # exact profile-likelihood end points of the Gaussian problem
    global function _mp_gauss_exact(i)   # i: 1-based parameter index
        k = (i - 1) ÷ 2
        x = gauss[gauss[:, 1] .== k, 2]; n = length(x)
        xb = sum(x) / n; s2 = sum(abs2, x .- xb) / n; s = sqrt(s2)
        if isodd(i)
            d = s * sqrt(exp(1 / n) - 1)
            return (xb - d, xb + d, d)
        end
        g(sig) = n * log(sig / s) + 0.5 * n * (s2 / sig^2 - 1) - 0.5
        function bis(a, b)
            fa = g(a)
            for _ in 1:200
                mid = 0.5 * (a + b); fm = g(mid)
                if (fm > 0) == (fa > 0)
                    a, fa = mid, fm
                else
                    b = mid
                end
            end
            0.5 * (a + b)
        end
        hi = bis(s, 10s); lo = bis(0.05s, s)
        return (lo, hi, 0.5 * (hi - lo))
    end
    global _mp_H = H
end

const _MP_PROBLEMS = [
    # name, f, up, x0, errors, lower-limited (1-based), |ΔMINOS| tol vs C++
    ("rosen2", _mp_rosen, 1.0, [-1.2, 1.0], [0.1, 0.1], Int[], 2e-4),
    ("quad4", _mp_quad4, 1.0, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4), Int[], 1e-9),
    ("gauss5", _mp_gauss, 0.5, [1.3, 1.0, 2.3, 1.0, 3.3, 1.0, 4.3, 1.0, 5.3, 1.0],
     fill(0.1, 10), Int[], 2e-5),
    ("bw6", _mp_bw, 1.0, [2.5, 5.1, 1.0, 0.9, 0.0, 0.0], fill(0.1, 6), [3], 2e-5),
    ("exp2", _mp_exp, 1.0, [1.5, 1.0], [0.1, 0.1], Int[], 5e-5),
]

# Counting FCN: records the scanned parameter's value per call while `scan[] > 0`.
function _mp_counted(f)
    scan = Ref(0); trace = Float64[]; ncalls = Ref(0)
    g = function (x)
        ncalls[] += 1
        s = scan[]
        s > 0 && push!(trace, x[s])
        return f(x)
    end
    return g, scan, trace, ncalls
end
# distinct consecutive values of the scanned parameter = the probe sequence
# (one inner minimisation per entry), in order
function _mp_probes(trace)
    out = Float64[]; prev = NaN
    for v in trace
        v == prev || (push!(out, v); prev = v)
    end
    out
end
_mp_nprobes(trace) = length(_mp_probes(trace))

function _mp_build(fcn, x0, e0, up, lowlim; strategy, tol, names)
    kw = Dict{Symbol,Any}(Symbol("limit_" * names[i]) => (0.0, nothing) for i in lowlim)
    Minuit(fcn, copy(x0); name = names, errors = copy(e0), up = up,
           strategy = strategy, tol = tol, kw...)
end

# q = (F_profile − F_min)/up at p_i = v, others re-minimised (Strategy(2), tol 1e-4)
function _mp_q(f, vals, errs, names, lowlim, up, fmin, i, v)
    n = length(vals)
    red(y) = begin
        full = Vector{Float64}(undef, n)
        full[1:i-1] .= y[1:i-1]; full[i] = v; full[i+1:n] .= y[i:n-1]
        f(full)
    end
    keep = [j for j in 1:n if j != i]
    rlow = [k < i ? k : k - 1 for k in lowlim if k != i]
    m2 = _mp_build(red, vals[keep], errs[keep], up, rlow;
                   strategy = 2, tol = 1e-4, names = names[keep])
    migrad!(m2; strategy = Strategy(2), tol = 1e-4)
    @test m2.valid
    return (m2.fval - fmin) / up
end

@testset "MINOS crossing parity with C++ MnFunctionCross" begin
    @test _MP_REF["strategy"] == 1
    for (name, f, up, x0, e0, lowlim, dtol) in _MP_PROBLEMS
        ref = _MP_REF["problems"][name]
        @testset "$name" begin
            g, scan, trace, ncalls = _mp_counted(f)
            n = length(x0)
            names = ["p$(i-1)" for i in 1:n]
            m = _mp_build(g, x0, e0, up, lowlim; strategy = 1, tol = 0.1, names = names)
            migrad!(m; strategy = Strategy(1), tol = 0.1)
            hesse(m; strategy = Strategy(1))
            @test m.valid
            # MIGRAD + HESSE already agree with C++ call for call
            @test ncalls[] == ref["nfcn_migrad"] + ref["nfcn_hesse"]
            @test m.fval ≈ ref["fval"] atol = 1e-6 * max(1.0, abs(ref["fval"]))
            nfcn_before = m.nfcn
            vals = collect(Float64, m.values); errs = collect(Float64, m.errors)
            minos_total = 0
            for i in 1:n
                r = ref["minos"][i]
                scan[] = i; empty!(trace)
                c0 = ncalls[]
                minos!(m, i; strategy = Strategy(1), tol = 0.1)
                dc = ncalls[] - c0
                scan[] = 0
                e = m.minos_errors[i]
                @testset "par $(i-1)" begin
                    @test NativeMinuit.is_valid(e)
                    @test e.upper_valid && e.lower_valid
                    @test !e.upper_par_limit && !e.lower_par_limit
                    @test e.nfcn == dc                       # MinosError.nfcn is the true count
                    minos_total += dc
                    # (3) same crossing-search structure as C++: the ordered
                    # probe positions, not just their number ...
                    probes = _mp_probes(trace)
                    @test length(probes) == length(r["probes"])
                    scale_p = abs(r["upper"]) + abs(r["lower"])
                    for (k, rp) in enumerate(r["probes"])
                        k <= length(probes) || break
                        @test abs(probes[k] - rp[1]) <= 1e-3 * scale_p
                    end
                    # ... same end points to the inner-MIGRAD tolerance ...
                    scale = abs(r["upper"]) + abs(r["lower"])
                    @test abs(e.upper - r["upper"]) <= dtol * scale
                    @test abs(e.lower - r["lower"]) <= dtol * scale
                    # ... and FCN calls within a few percent of C++ or fewer
                    # (fewer on the warm-restarted unbounded path; the bounded
                    # path re-seeds each probe and costs ~6% more on bw6's Γ)
                    @test dc <= ceil(Int, 1.1 * r["nfcn"])
                    # (1) crossing quality at the Minuit2 level
                    q_up = _mp_q(f, vals, errs, names, lowlim, up, m.fval, i, e.min_par_value + e.upper)
                    q_lo = _mp_q(f, vals, errs, names, lowlim, up, m.fval, i, e.min_par_value + e.lower)
                    @test abs(q_up - 1) <= 2e-4
                    @test abs(q_lo - 1) <= 2e-4
                    # (2) closed-form profile intervals
                    if name == "gauss5"
                        lo_x, hi_x, hw = _mp_gauss_exact(i)
                        @test abs(e.min_par_value + e.upper - hi_x) <= 2e-4 * hw
                        @test abs(e.min_par_value + e.lower - lo_x) <= 2e-4 * hw
                    elseif name == "quad4"
                        d = sqrt(2 * up * inv(_mp_H)[i, i])    # MINOS = HESSE exactly
                        @test e.upper ≈ d atol = 1e-10
                        @test e.lower ≈ -d atol = 1e-10
                    end
                end
            end
            # m.nfcn accumulates the MINOS calls (iminuit convention) and is
            # exactly the independent count of every call made on this fit
            @test m.nfcn == nfcn_before + minos_total
            @test m.nfcn == ncalls[]
            hesse(m; strategy = Strategy(1))
            @test m.nfcn == ncalls[]                 # HESSE adds, MINOS kept, no double count
        end
    end

    @testset "maxcall is the budget of each inner MIGRAD (C++ semantics)" begin
        # Rosenbrock y: 11 probes of at most 19 calls each in the reference
        # (minos_parity_cpp.json); a budget of 40 per inner MIGRAD succeeds
        # in Minuit2 / iminuit, and would fail if applied to the whole search.
        g, scan, trace, ncalls = _mp_counted(_mp_rosen)
        m = _mp_build(g, [-1.2, 1.0], [0.1, 0.1], 1.0, Int[]; strategy = 1, tol = 0.1, names = ["p0", "p1"])
        migrad!(m); hesse(m)
        minos!(m, 2; maxcall = 40)
        e = m.minos_errors[2]
        r = _MP_REF["problems"]["rosen2"]["minos"][2]
        @test e.lower_valid && e.upper_valid
        @test !e.lower_fcn_limit && !e.upper_fcn_limit
        @test abs(e.upper - r["upper"]) <= 2e-4 * (abs(r["upper"]) + abs(r["lower"]))
        @test abs(e.lower - r["lower"]) <= 2e-4 * (abs(r["upper"]) + abs(r["lower"]))
    end

    @testset "sigma = 2: aim, inner tolerance and pre-shift all scale (closed form)" begin
        # Gaussian means have the exact 2σ profile interval x̄ ± s·√(e^{4/n} − 1).
        g, _, _, _ = _mp_counted(_mp_gauss)
        names = ["p$(i-1)" for i in 1:10]
        m = _mp_build(g, [1.3, 1.0, 2.3, 1.0, 3.3, 1.0, 4.3, 1.0, 5.3, 1.0], fill(0.1, 10), 0.5, Int[];
                      strategy = 1, tol = 0.1, names = names)
        migrad!(m); hesse(m)
        for i in (1, 5, 9)
            minos!(m, i; sigma = 2.0)
            e = m.minos_errors[i]
            @test e.upper_valid && e.lower_valid
            k = (i - 1) ÷ 2
            lo1, hi1, hw1 = _mp_gauss_exact(i)
            xb = 0.5 * (lo1 + hi1)
            n = 50
            hw2 = hw1 * sqrt(exp(4 / n) - 1) / sqrt(exp(1 / n) - 1)
            @test abs(e.min_par_value + e.upper - (xb + hw2)) <= 2e-4 * hw2
            @test abs(e.min_par_value + e.lower - (xb - hw2)) <= 2e-4 * hw2
            # ΔNLL/up at the end points is σ² = 4
            vals = collect(Float64, m.values); errs = collect(Float64, m.errors)
            for v in (e.min_par_value + e.upper, e.min_par_value + e.lower)
                q = _mp_q(_mp_gauss, vals, errs, names, Int[], 0.5, m.fval, i, v)
                @test abs(q - 4) <= 1e-3
            end
        end
    end

    @testset "sigma reaches the inner minimisations (discriminating)" begin
        # (a) At sigma = 0.05 the crossing aim is fmin + 0.0025·up. Minuit2 /
        # iminuit run the inner MIGRADs at the σ²-scaled errordef, so their EDM
        # goal is 0.002·tol·up·σ²; with the unscaled goal the inner minima are
        # only good to ~1e-4·up, i.e. ~4% of the aim, and the end points of
        # the correlated quadratic (exact: ±σ·√(2·up·V_ii)) miss by that much.
        V = inv(_mp_H)
        g, _, _, _ = _mp_counted(_mp_quad4)
        m = _mp_build(g, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4), 1.0, Int[]; strategy = 1, tol = 0.1,
                      names = ["p0", "p1", "p2", "p3"])
        migrad!(m); hesse(m)
        for i in 1:4
            minos!(m, i; sigma = 0.05)
            e = m.minos_errors[i]
            ex = 0.05 * sqrt(2 * V[i, i])
            @test e.upper_valid && e.lower_valid
            @test abs(e.upper - ex) <= 2e-4 * ex
            @test abs(-e.lower - ex) <= 2e-4 * ex
        end
        # (b) The correlated starting displacement of the OTHER parameters at
        # the first probe (C++ MnMinos.cxx:140-146, xunit = √(up_eff/m_ii))
        # scales with σ; the scanned parameter's own step (the HESSE error)
        # does not. Observed through the first FCN evaluation of the search.
        first_x = Ref(Float64[]); arm = Ref(false)
        gq = x -> (arm[] && (first_x[] = collect(Float64, x); arm[] = false); _mp_quad4(x))
        m2 = _mp_build(gq, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4), 1.0, Int[]; strategy = 1, tol = 0.1,
                       names = ["p0", "p1", "p2", "p3"])
        migrad!(m2); hesse(m2)
        xh = collect(Float64, m2.values)
        arm[] = true; minos!(m2, 1; sigma = 1.0); d1 = first_x[] .- xh
        arm[] = true; minos!(m2, 1; sigma = 2.0); d2 = first_x[] .- xh
        @test d1[1] ≈ sqrt(2 * V[1, 1]) rtol = 1e-6         # the HESSE step
        @test d2[1] ≈ d1[1] rtol = 1e-12                    # unchanged at σ = 2
        for k in 2:4
            @test abs(d1[k]) > 0.05                         # a genuine displacement …
            @test d2[k] ≈ 2 * d1[k] rtol = 1e-9             # … that doubles with σ
        end
        # (c) A contour at sigma = 0.01: the axis points come from an inner
        # minimisation of their own; unscaled, their profiled value misses the
        # aim by a few percent of it (and the ray points similarly), scaled
        # they lie on the contour to ~1e-4.
        fc(p) = (w = p[3] - 0.1 * p[1] - 0.6 * p[2];
                 p[1]^2 + 2 * p[2]^2 + 0.5 * p[1] * p[2] + w^2 + 0.1 * w^4)
        cf = CostFunction(fc, 1.0)
        fm = migrad(cf, [0.0, 0.0, 0.0], [0.1, 0.1, 0.1]; strategy = Strategy(1))
        c = contour_exact(fm, cf, 1, 2; npoints = 8, sigma = 0.01, strategy = Strategy(1))
        @test c.valid && length(c.points) == 8
        for pt in c.full_points
            q = (fc(pt) - fval(fm)) / (1.0 * 0.01^2)
            @test abs(q - 1) <= 5e-4
        end
        # (d) The inner minimisations carry the σ²-scaled errordef itself —
        # not merely a σ²-scaled tolerance, which would leave the numerical
        # gradient / HESSE step sizes (C++ reads Up there) at the original
        # errordef while reproducing the EDM goal. Observed on the inner
        # minima's own `up`, which only the errordef route sets.
        cf4 = CostFunction(_mp_quad4, 1.0)
        fm4 = migrad(cf4, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4); strategy = Strategy(1))
        st = fm4.state
        inner1, _ = NativeMinuit._migrad_with_fixed(cf4, st, 1, st.parameters.x[1] + 0.3;
                                                    tol = 0.05, maxcalls = 1000,
                                                    prec = MachinePrecision(), up_inner = 4.0)
        @test inner1.up == 4.0
        innerm, _ = NativeMinuit._migrad_with_multi_fixed(cf4, st, [1, 2],
                                                          st.parameters.x[1:2] .+ 0.2;
                                                          tol = 0.05, maxcalls = 1000,
                                                          prec = MachinePrecision(), up_inner = 0.25)
        @test innerm.up == 0.25
        @test NativeMinuit._with_errordef(cf4, 4.0).up == 4.0
        @test NativeMinuit._with_errordef(cf4, 1.0) === cf4
        cfg = NativeMinuit.CostFunctionWithGradient(_mp_quad4, x -> _mp_H * x, 1.0)
        @test NativeMinuit._with_errordef(cfg, 4.0).up == 4.0
        @test NativeMinuit._fix_one_param(cf4, 1, 0.5, 4; up = 2.5).up == 2.5
        @test NativeMinuit._fix_multi_params(cf4, [1, 2], [0.5, 0.5], 4; up = 2.5).up == 2.5
        # (e) … and on the production paths: the probe trace of a real
        # `minos!` (unbounded and bounded) and of a real contour at sigma = 2
        # reports the inner minimisations' errordef as 4, never 1.
        innerups(f) = begin
            logs, _ = Test.collect_test_logs(f)
            vals = Float64[]
            for l in logs
                for mm in eachmatch(r"innerup=([0-9.eE+-]+)", string(l.message))
                    push!(vals, parse(Float64, mm.captures[1]))
                end
            end
            vals
        end
        mu = _mp_build(_mp_quad4, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4), 1.0, Int[];
                       strategy = 1, tol = 0.1, names = ["p0", "p1", "p2", "p3"])
        migrad!(mu); hesse(mu)
        v = innerups(() -> minos!(mu, 2; sigma = 2.0, print_level = 2))
        @test length(v) >= 2 && all(==(4.0), v)
        v1 = innerups(() -> minos!(mu, 2; sigma = 1.0, print_level = 2))
        @test length(v1) >= 2 && all(==(1.0), v1)
        mb = _mp_build(_mp_quad4, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4), 1.0, Int[];
                       strategy = 1, tol = 0.1, names = ["p0", "p1", "p2", "p3"])
        set_limits!(mb, 1, -10.0, 10.0)            # bounded scanned parameter → bounded path
        migrad!(mb); hesse(mb)
        vb = innerups(() -> minos!(mb, 1; sigma = 2.0, print_level = 2))
        @test length(vb) >= 2 && all(==(4.0), vb)
        vc = innerups(() -> contour_exact(fm4, cf4, 1, 2; npoints = 6, sigma = 2.0,
                                          strategy = Strategy(1), print_level = 2))
        @test length(vc) >= 6 && all(==(4.0), vc)   # MINOS probes, axis points, rays
        # (f) Two-parameter contours fix every parameter on each ray, so the
        # ray probes are bare evaluations without an inner MIGRAD; their
        # result must still carry the σ²-scaled errordef (C++ keeps the
        # effective Up through the no-free-parameter builder). The
        # four-parameter fixture above never reaches this branch.
        cf2 = CostFunction(x -> x[1]^2 + x[2]^2, 1.0)
        fm2 = migrad(cf2, [0.0, 0.0], [0.1, 0.1]; strategy = Strategy(1))
        inner2, nf2 = NativeMinuit._migrad_with_multi_fixed(cf2, fm2.state, [1, 2], [0.3, 0.4];
                                                            tol = 0.05, maxcalls = 1000,
                                                            prec = MachinePrecision(), up_inner = 4.0)
        @test nf2 == 1 && inner2.up == 4.0 && NativeMinuit.fval(inner2) ≈ 0.25
        v2 = innerups(() -> contour_exact(fm2, cf2, 1, 2; npoints = 6, sigma = 2.0,
                                          strategy = Strategy(1), print_level = 2))
        @test length(v2) >= 6 && all(==(4.0), v2)   # all-fixed rays included
    end

    @testset "a bound-touching search that fails keeps its failure (C++ MnCross flags)" begin
        # Upper bound at 0.5 truncates the HESSE step, so the first probe sits
        # at the bound; with a one-call budget it exits on the call limit.
        # Minuit2 / iminuit report an invalid upper side with the call-limit
        # flag and NO parameter-limit flag; the side must not be published as
        # a valid at-limit result.
        m = Minuit(x -> x[1]^2 + x[2]^2, [0.0, 0.0]; errors = [0.1, 0.1],
                   name = ["p0", "p1"], limit_p0 = (nothing, 0.5))
        migrad!(m); hesse(m)
        minos!(m, 1; maxcall = 1)
        e = m.minos_errors[1]
        @test !e.upper_valid
        @test e.upper_fcn_limit
        @test !e.upper_par_limit
        # a genuine at-limit termination (probe converged below the aim at the
        # bound) is still reported as a valid at-limit side with the bound distance
        m2 = Minuit(x -> x[1]^2 + x[2]^2, [0.0, 0.0]; errors = [0.1, 0.1],
                    name = ["p0", "p1"], limit_p0 = (nothing, 0.5))
        migrad!(m2); hesse(m2); minos!(m2, 1)
        e2 = m2.minos_errors[1]
        @test e2.upper_valid && e2.upper_par_limit && !e2.upper_fcn_limit
        @test e2.upper ≈ 0.5 - e2.min_par_value atol = 1e-9
    end

    @testset "inner-MIGRAD seed covariance is the conditional (squeezed) covariance" begin
        # Fixing parameters `idxs` leaves the inverse of the reduced Hessian,
        # not the minor of the covariance (which is the marginal one).
        V = inv(_mp_H)
        err = NativeMinuit.MinimumError(V, 0.0)
        for idxs in ((1,), (3,), (2, 4), (1, 2))
            keep = [j for j in 1:4 if !(j in idxs)]
            expected = inv(_mp_H[keep, keep])
            got = NativeMinuit._conditional_prior_cov(err, idxs)
            @test got ≈ expected rtol = 1e-12
            @test !(got ≈ V[keep, keep])          # the marginal minor is different
        end
    end
end

@testset "hesse(m) / minos!(m) honour m.strategy (iminuit parity)" begin
    names = ["p$(i-1)" for i in 1:10]
    x0 = [1.3, 1.0, 2.3, 1.0, 3.3, 1.0, 4.3, 1.0, 5.3, 1.0]
    # fresh fit each time: a second HESSE on an already-refined state uses the
    # refined step sizes and is not bit-identical to the first
    function fresh(s)
        g, _, _, _ = _mp_counted(_mp_gauss)
        m = _mp_build(g, x0, fill(0.1, 10), 0.5, Int[]; strategy = s, tol = 0.1, names = names)
        migrad!(m)
        return m
    end
    for s in (0, 2)
        m_def = fresh(s); @test m_def.strategy == Strategy(s)
        hesse(m_def)
        m_exp = fresh(s); hesse(m_exp; strategy = Strategy(s))
        @test m_def.covariance == m_exp.covariance            # default == m.strategy
        # (on this near-quadratic likelihood HESSE at strategies 1 and 2
        # early-exit to identical covariances, so the negative check — that
        # the default is NOT a fixed Strategy(1) — is made on Rosenbrock below)
        minos!(m_def, 2); minos!(m_exp, 2; strategy = Strategy(s))
        e_def, e_exp = m_def.minos_errors[2], m_exp.minos_errors[2]
        @test e_def.upper == e_exp.upper && e_def.lower == e_exp.lower
        @test e_def.nfcn == e_exp.nfcn
    end
    # HESSE's FCN call count on a 2-parameter fit is 6 at Strategy(0) and 10
    # at Strategy(1)/(2) (one fewer Hessian-gradient cycle), so counting the
    # calls of `hesse(m)` under m.strategy = 0 and 2 pins the default to the
    # stored strategy; a regression to a fixed Strategy(1) would give 10 in
    # both cases and fail the first assertion below.
    function hesse_calls(s; explicit = nothing)
        g, _, _, ncalls = _mp_counted(_mp_rosen)
        m = Minuit(g, [-1.2, 1.0]; name = ["x", "y"], errors = [0.1, 0.1],
                   strategy = s, tol = 0.1)
        migrad!(m)
        c0 = ncalls[]
        explicit === nothing ? hesse(m) : hesse(m; strategy = Strategy(explicit))
        return ncalls[] - c0
    end
    c0_def, c2_def = hesse_calls(0), hesse_calls(2)
    c0_exp, c1_exp, c2_exp = hesse_calls(0; explicit = 0), hesse_calls(0; explicit = 1), hesse_calls(0; explicit = 2)
    @test c0_exp != c2_exp                        # the observable discriminates
    @test c0_def == c0_exp && c2_def == c2_exp    # default == m.strategy
    @test c0_def != c1_exp                        # and not a fixed Strategy(1)
    # MINOS: the inner MIGRADs run at m.strategy − 1; Rosenbrock's y search
    # iterates, so Strategy(0) and Strategy(2) differ measurably
    function fresh_rosen(s)
        m = Minuit(_mp_rosen, [-1.2, 1.0]; name = ["x", "y"], errors = [0.1, 0.1],
                   strategy = s, tol = 0.1)
        migrad!(m); hesse(m; strategy = Strategy(1))
        return m
    end
    m_def = fresh_rosen(2); m_s2 = fresh_rosen(2); m_s0 = fresh_rosen(2)
    minos!(m_def, 2); minos!(m_s2, 2; strategy = Strategy(2)); minos!(m_s0, 2; strategy = Strategy(0))
    e_def, e_s2, e_s0 = m_def.minos_errors[2], m_s2.minos_errors[2], m_s0.minos_errors[2]
    @test e_def.nfcn == e_s2.nfcn && e_def.upper == e_s2.upper && e_def.lower == e_s2.lower
    @test e_s0.nfcn != e_s2.nfcn || e_s0.upper != e_s2.upper || e_s0.lower != e_s2.lower  # discriminating
    # a new fit result restarts the count; HESSE on the same fit keeps it
    m = fresh(1); n_fit = m.nfcn
    minos!(m, 1); n_minos = m.minos_errors[1].nfcn
    @test m.nfcn == n_fit + n_minos
    hesse(m)
    @test m.nfcn > n_fit + n_minos                            # + HESSE calls, MINOS kept
    migrad!(m)
    @test m.nfcn < n_fit + n_minos                            # fresh count after a new fit
end
