# SPDX-License-Identifier: LGPL-2.1-or-later
#
# MINOS crossing-search parity with C++ Minuit2 (MnFunctionCross).
#
# Reference: test/reference_data/minos_parity_cpp.json, generated by
# tools/minos_parity_trace.cxx against the pinned Minuit2 6.24.0 (MIGRAD +
# HESSE + MINOS at Strategy(1), tol 0.1) on five generic problems whose data
# are the minos_parity_*.txt files next to it. Each objective is wrapped in
# a counting FCN that records the scanned parameter's value per call during
# MINOS, so the inner minimisations ("probes") of the crossing search are
# observable on both sides without instrumenting the algorithm.
#
# What is pinned:
#  1. Crossing quality. For each end point x̂ ± δ, fixing the parameter there
#     and re-minimising the rest (Strategy(2), tol 1e-4) gives
#     q = (F_profile − F_min)/up; a perfect crossing has q = 1. Through
#     v0.7.3 the search substituted a fictitious point for the α=0 inner
#     MIGRAD and had no quadratic early exit, which biased the end points
#     by up to the 0.01·up crossing tolerance (|q−1| ≈ 1e-2); Minuit2 and
#     the C++-faithful port reach ≲ 1e-4.
#  2. The Gaussian problem has closed-form profile-likelihood intervals
#     (means: x̄ ± s·√(e^{1/n} − 1); widths: n·ln(σ/s) + n/2·(s²/σ² − 1) = 1/2),
#     compared as end-point POSITIONS so the MIGRAD minimum's own
#     displacement is included, as in the external benchmark.
#  3. The probe sequence (number of inner minimisations per parameter) equals
#     the C++ one, and the MINOS end points agree with C++ to the inner-MIGRAD
#     tolerance. Total FCN calls are at most the C++ count: NativeMinuit
#     warm-restarts the inner MIGRAD from the previous probe's gradient steps
#     and covariance and skips the iteration when the seed is already
#     converged (see `_migrad_loop`), where C++ re-seeds the gradient from the
#     parameter errors and always runs one line search — a documented,
#     deliberate difference in cost per probe, not in the crossing found.

using JSON
# Whitespace-separated numeric table (the minos_parity_*.txt data files),
# read without DelimitedFiles (not a standard library since Julia 1.9).
function _mp_readrows(path)
    rows = [parse.(Float64, split(l)) for l in eachline(path) if !isempty(strip(l))]
    return permutedims(reduce(hcat, rows))
end

const _MP_DIR = joinpath(@__DIR__, "reference_data")
const _MP_REF = JSON.parsefile(joinpath(_MP_DIR, "minos_parity_cpp.json"))

# ── The five problems (identical to tools/minos_parity_trace.cxx) ──────────
let gauss = _mp_readrows(joinpath(_MP_DIR, "minos_parity_gauss5.txt")),
    bw = _mp_readrows(joinpath(_MP_DIR, "minos_parity_bw6.txt")),
    ex = _mp_readrows(joinpath(_MP_DIR, "minos_parity_exp2.txt")),
    H = _mp_readrows(joinpath(_MP_DIR, "minos_parity_quad4_H.txt"))

    global _mp_rosen(p) = (1 - p[1])^2 + 100 * (p[2] - p[1]^2)^2
    global function _mp_quad4(p)
        s = 0.0
        for i in 1:4, j in 1:4
            s += 0.5 * p[i] * H[i, j] * p[j]
        end
        s
    end
    global function _mp_gauss(p)
        s = 0.0
        @inbounds for r in 1:size(gauss, 1)
            k = Int(gauss[r, 1]); mu = p[2k + 1]; sg = p[2k + 2]
            sg <= 0 && return 1e30
            d = gauss[r, 2] - mu
            s += log(sg) + 0.5 * d * d / (sg * sg)
        end
        s
    end
    global function _mp_bw(p)
        s = 0.0
        @inbounds for r in 1:size(bw, 1)
            x = bw[r, 1]
            m = p[1] * (p[3] * p[3] / 4) / ((x - p[2])^2 + p[3] * p[3] / 4) +
                p[4] + p[5] * (x - 5) + p[6] * (x - 5)^2
            d = (bw[r, 2] - m) / 0.05
            s += d * d
        end
        s
    end
    global function _mp_exp(p)
        s = 0.0
        @inbounds for r in 1:size(ex, 1)
            m = p[1] * exp(-ex[r, 1] / p[2]); d = (ex[r, 2] - m) / 0.02
            s += d * d
        end
        s
    end
    # exact profile-likelihood end points of the Gaussian problem
    global function _mp_gauss_exact(i)   # i: 1-based parameter index
        k = (i - 1) ÷ 2
        x = gauss[gauss[:, 1] .== k, 2]; n = length(x)
        xb = sum(x) / n; s2 = sum(abs2, x .- xb) / n; s = sqrt(s2)
        if isodd(i)
            d = s * sqrt(exp(1 / n) - 1)
            return (xb - d, xb + d, d)
        end
        g(sig) = n * log(sig / s) + 0.5 * n * (s2 / sig^2 - 1) - 0.5
        function bis(a, b)
            fa = g(a)
            for _ in 1:200
                mid = 0.5 * (a + b); fm = g(mid)
                if (fm > 0) == (fa > 0)
                    a, fa = mid, fm
                else
                    b = mid
                end
            end
            0.5 * (a + b)
        end
        hi = bis(s, 10s); lo = bis(0.05s, s)
        return (lo, hi, 0.5 * (hi - lo))
    end
    global _mp_H = H
end

const _MP_PROBLEMS = [
    # name, f, up, x0, errors, lower-limited (1-based), |ΔMINOS| tol vs C++
    ("rosen2", _mp_rosen, 1.0, [-1.2, 1.0], [0.1, 0.1], Int[], 2e-4),
    ("quad4", _mp_quad4, 1.0, [1.0, 1.0, 1.0, 1.0], fill(0.1, 4), Int[], 1e-9),
    ("gauss5", _mp_gauss, 0.5, [1.3, 1.0, 2.3, 1.0, 3.3, 1.0, 4.3, 1.0, 5.3, 1.0],
     fill(0.1, 10), Int[], 2e-5),
    ("bw6", _mp_bw, 1.0, [2.5, 5.1, 1.0, 0.9, 0.0, 0.0], fill(0.1, 6), [3], 2e-5),
    ("exp2", _mp_exp, 1.0, [1.5, 1.0], [0.1, 0.1], Int[], 5e-5),
]

# Counting FCN: records the scanned parameter's value per call while `scan[] > 0`.
function _mp_counted(f)
    scan = Ref(0); trace = Float64[]; ncalls = Ref(0)
    g = function (x)
        ncalls[] += 1
        s = scan[]
        s > 0 && push!(trace, x[s])
        return f(x)
    end
    return g, scan, trace, ncalls
end
# number of distinct consecutive values = inner minimisations (probes)
function _mp_nprobes(trace)
    n = 0; prev = NaN
    for v in trace
        v == prev || (n += 1; prev = v)
    end
    n
end

function _mp_build(fcn, x0, e0, up, lowlim; strategy, tol, names)
    kw = Dict{Symbol,Any}(Symbol("limit_" * names[i]) => (0.0, nothing) for i in lowlim)
    Minuit(fcn, copy(x0); name = names, errors = copy(e0), up = up,
           strategy = strategy, tol = tol, kw...)
end

# q = (F_profile − F_min)/up at p_i = v, others re-minimised (Strategy(2), tol 1e-4)
function _mp_q(f, vals, errs, names, lowlim, up, fmin, i, v)
    n = length(vals)
    red(y) = begin
        full = Vector{Float64}(undef, n)
        full[1:i-1] .= y[1:i-1]; full[i] = v; full[i+1:n] .= y[i:n-1]
        f(full)
    end
    keep = [j for j in 1:n if j != i]
    rlow = [k < i ? k : k - 1 for k in lowlim if k != i]
    m2 = _mp_build(red, vals[keep], errs[keep], up, rlow;
                   strategy = 2, tol = 1e-4, names = names[keep])
    migrad!(m2; strategy = Strategy(2), tol = 1e-4)
    @test m2.valid
    return (m2.fval - fmin) / up
end

@testset "MINOS crossing parity with C++ MnFunctionCross" begin
    @test _MP_REF["strategy"] == 1
    for (name, f, up, x0, e0, lowlim, dtol) in _MP_PROBLEMS
        ref = _MP_REF["problems"][name]
        @testset "$name" begin
            g, scan, trace, ncalls = _mp_counted(f)
            n = length(x0)
            names = ["p$(i-1)" for i in 1:n]
            m = _mp_build(g, x0, e0, up, lowlim; strategy = 1, tol = 0.1, names = names)
            migrad!(m; strategy = Strategy(1), tol = 0.1)
            hesse(m; strategy = Strategy(1))
            @test m.valid
            # MIGRAD + HESSE already agree with C++ call for call
            @test ncalls[] == ref["nfcn_migrad"] + ref["nfcn_hesse"]
            @test m.fval ≈ ref["fval"] atol = 1e-6 * max(1.0, abs(ref["fval"]))
            nfcn_before = m.nfcn
            vals = collect(Float64, m.values); errs = collect(Float64, m.errors)
            minos_total = 0
            for i in 1:n
                r = ref["minos"][i]
                scan[] = i; empty!(trace)
                c0 = ncalls[]
                minos!(m, i; strategy = Strategy(1), tol = 0.1)
                dc = ncalls[] - c0
                scan[] = 0
                e = m.minos_errors[i]
                @testset "par $(i-1)" begin
                    @test NativeMinuit.is_valid(e)
                    @test e.upper_valid && e.lower_valid
                    @test !e.upper_par_limit && !e.lower_par_limit
                    @test e.nfcn == dc                       # MinosError.nfcn is the true count
                    minos_total += dc
                    # (3) same crossing-search structure as C++ ...
                    @test _mp_nprobes(trace) == length(r["probes"])
                    # ... same end points to the inner-MIGRAD tolerance ...
                    scale = abs(r["upper"]) + abs(r["lower"])
                    @test abs(e.upper - r["upper"]) <= dtol * scale
                    @test abs(e.lower - r["lower"]) <= dtol * scale
                    # ... and FCN calls within a few percent of C++ or fewer
                    # (fewer on the warm-restarted unbounded path; the bounded
                    # path re-seeds each probe and costs ~6% more on bw6's Γ)
                    @test dc <= ceil(Int, 1.1 * r["nfcn"])
                    # (1) crossing quality at the Minuit2 level
                    q_up = _mp_q(f, vals, errs, names, lowlim, up, m.fval, i, e.min_par_value + e.upper)
                    q_lo = _mp_q(f, vals, errs, names, lowlim, up, m.fval, i, e.min_par_value + e.lower)
                    @test abs(q_up - 1) <= 2e-4
                    @test abs(q_lo - 1) <= 2e-4
                    # (2) closed-form profile intervals
                    if name == "gauss5"
                        lo_x, hi_x, hw = _mp_gauss_exact(i)
                        @test abs(e.min_par_value + e.upper - hi_x) <= 2e-4 * hw
                        @test abs(e.min_par_value + e.lower - lo_x) <= 2e-4 * hw
                    elseif name == "quad4"
                        d = sqrt(2 * up * inv(_mp_H)[i, i])    # MINOS = HESSE exactly
                        @test e.upper ≈ d atol = 1e-10
                        @test e.lower ≈ -d atol = 1e-10
                    end
                end
            end
            # m.nfcn accumulates the MINOS calls (iminuit convention)
            @test m.nfcn == nfcn_before + minos_total
        end
    end
end

@testset "hesse(m) / minos!(m) honour m.strategy (iminuit parity)" begin
    names = ["p$(i-1)" for i in 1:10]
    x0 = [1.3, 1.0, 2.3, 1.0, 3.3, 1.0, 4.3, 1.0, 5.3, 1.0]
    # fresh fit each time: a second HESSE on an already-refined state uses the
    # refined step sizes and is not bit-identical to the first
    function fresh(s)
        g, _, _, _ = _mp_counted(_mp_gauss)
        m = _mp_build(g, x0, fill(0.1, 10), 0.5, Int[]; strategy = s, tol = 0.1, names = names)
        migrad!(m)
        return m
    end
    for s in (0, 2)
        m_def = fresh(s); @test m_def.strategy == Strategy(s)
        hesse(m_def)
        m_exp = fresh(s); hesse(m_exp; strategy = Strategy(s))
        @test m_def.covariance == m_exp.covariance            # default == m.strategy
        # (on this near-quadratic likelihood HESSE at strategies 1 and 2
        # early-exit to identical covariances, so the negative check — that
        # the default is NOT a fixed Strategy(1) — is made on Rosenbrock below)
        minos!(m_def, 2); minos!(m_exp, 2; strategy = Strategy(s))
        e_def, e_exp = m_def.minos_errors[2], m_exp.minos_errors[2]
        @test e_def.upper == e_exp.upper && e_def.lower == e_exp.lower
        @test e_def.nfcn == e_exp.nfcn
    end
    # Rosenbrock: HESSE strategies differ measurably, so the default must
    # follow m.strategy = 2 and not a fixed Strategy(1)/Strategy(0)
    function fresh_rosen(s)
        m = Minuit(_mp_rosen, [-1.2, 1.0]; name = ["x", "y"], errors = [0.1, 0.1],
                   strategy = s, tol = 0.1)
        migrad!(m)
        return m
    end
    m_def = fresh_rosen(2); hesse(m_def)
    m_s2 = fresh_rosen(2); hesse(m_s2; strategy = Strategy(2))
    m_s1 = fresh_rosen(2); hesse(m_s1; strategy = Strategy(1))
    m_s0 = fresh_rosen(2); hesse(m_s0; strategy = Strategy(0))
    @test m_def.covariance == m_s2.covariance
    @test m_s1.covariance == m_s2.covariance || m_def.covariance != m_s1.covariance
    @test m_s0.covariance == m_s2.covariance || m_def.covariance != m_s0.covariance
    # HESSE early-exits to the same covariance at every strategy on these
    # converged minima; the discriminating observable is the MINOS search on
    # Rosenbrock's y, whose inner MIGRADs run at strategy − 1 and iterate.
    minos!(m_def, 2); minos!(m_s2, 2; strategy = Strategy(2)); minos!(m_s0, 2; strategy = Strategy(0))
    e_def, e_s2, e_s0 = m_def.minos_errors[2], m_s2.minos_errors[2], m_s0.minos_errors[2]
    @test e_def.nfcn == e_s2.nfcn && e_def.upper == e_s2.upper && e_def.lower == e_s2.lower
    @test e_s0.nfcn != e_s2.nfcn || e_s0.upper != e_s2.upper || e_s0.lower != e_s2.lower  # discriminating
    # a new fit result restarts the count; HESSE on the same fit keeps it
    m = fresh(1); n_fit = m.nfcn
    minos!(m, 1); n_minos = m.minos_errors[1].nfcn
    @test m.nfcn == n_fit + n_minos
    hesse(m)
    @test m.nfcn > n_fit + n_minos                            # + HESSE calls, MINOS kept
    migrad!(m)
    @test m.nfcn < n_fit + n_minos                            # fresh count after a new fit
end
