# SPDX-License-Identifier: LGPL-2.1-or-later
#
# C++ MINOS oracle agreement test — Phase 1 完成判据 #5.
#
# Asserts that JuMinuit's MINOS asymmetric errors agree with C++
# `MnMinos` to ~1e-8 on a set of unbounded fits. Oracle JSON is
# generated by `tools/cpp_trace_harness.cxx :: run_minos_case`
# (one file per case, `<name>_minos.json`).
#
# For symmetric fits (quadratic FCN), the MINOS upper/lower errors
# should match each other and match the Hesse error to within
# numerical noise — useful sanity check on top of the absolute
# C++ comparison.

using JSON

# Map test name → (FCN, x0, errs0, atol_value, atol_minos).
#
# Tolerances are case-specific:
#  • Pure-quadratic FCNs (`quad_4d`, `quad_2d_shifted`) — MINOS is
#    exactly linear in the parameter, so Julia and C++ should agree
#    to ~1e-8 (the floating-point round-off level).
#  • Rosenbrock — iterative parabolic root-find converges with
#    EDM-controlled accuracy; the realistic Julia ↔ C++ agreement
#    is ~1e-4 (MIGRAD's tlr·up tolerance squared).
const MINOS_CASES = Dict{String,Tuple{Function,Vector{Float64},Vector{Float64},Float64,Float64}}(
    "rosenbrock_2d" => (
        x -> (1 - x[1])^2 + 100 * (x[2] - x[1]^2)^2,
        [-1.2, 1.0], [0.1, 0.1],
        1e-3, 1e-3,
    ),
    "quad_4d" => (
        x -> sum(abs2, x),
        [1.0, 1.0, 1.0, 1.0], [0.1, 0.1, 0.1, 0.1],
        1e-8, 1e-8,    # ROADMAP §4 #5: "MINOS errors agree to 1e-8 with C++ on Quad4F"
    ),
    "quad_2d_shifted" => (
        x -> (x[1] - 1)^2 + (x[2] - 2)^2,
        [0.0, 0.0], [0.1, 0.1],
        1e-8, 1e-8,
    ),
)

@testset "C++ JSON MINOS oracle parity — Phase 1 完成判据 #5" begin
    for (name, (f, x0, errs0, atol_v, atol_m)) in MINOS_CASES
        path = joinpath(@__DIR__, "reference_data", "$(name)_minos.json")
        @testset "$name MINOS vs C++ MnMinos" begin
            isfile(path) || (@warn "Oracle missing: $path"; continue)
            ref = JSON.parsefile(path)

            cf = CostFunction(f)
            # iminuit default: Strategy(1). C++ MnMinos's default strategy
            # also derives from the FunctionMinimum's strategy.
            fmin = migrad(cf, x0, errs0; strategy = Strategy(1))
            @test JuMinuit.is_valid(fmin)
            @test fval(fmin) ≈ ref["fval"] atol = atol_v

            ref_params = Float64.(ref["params"])
            for (i, exp_p) in enumerate(ref_params)
                @test Base.values(fmin)[i] ≈ exp_p atol = atol_v
            end

            # Run MINOS on each parameter and compare
            for (i, ref_entry) in enumerate(ref["minos"])
                @testset "par $i" begin
                    err = JuMinuit.minos(fmin, cf, i; strategy = Strategy(1))

                    @test JuMinuit.is_valid(err)
                    @test err.upper_valid == ref_entry["upper_valid"]
                    @test err.lower_valid == ref_entry["lower_valid"]

                    # Numerical agreement of asymmetric ± errors.
                    # Pure-quadratic FCNs: 1e-8 (ROADMAP §4 #5).
                    # Rosenbrock: 1e-3 — limited by MIGRAD's tlr·up
                    # convergence tolerance squared (the parabolic
                    # root-find inherits this from MIGRAD).
                    @test err.upper ≈ ref_entry["upper"] atol = atol_m
                    @test err.lower ≈ ref_entry["lower"] atol = atol_m

                    # Sanity: min_par_value matches MIGRAD's converged value
                    @test err.min_par_value ≈ ref_entry["min_value"] atol = atol_v
                end
            end
        end
    end
end
